"use client";

import { useState, useTransition } from "react";
import { Button } from "@/components/ui/button";
import { Field, Input } from "@/components/ui/input";
import { Alert, Modal } from "@/components/ui/modal";
import { createPartAction } from "@/server/actions/parts.actions";
import { searchPartsForPosAction } from "@/server/actions/search.actions";
import type { PosPartRow } from "@/server/services/parts.service";

export function QuickPartModal({ initialName, onClose, onCreated }: { initialName: string; onClose: () => void; onCreated: (part: PosPartRow) => void }) {
  const [nameAr, setNameAr] = useState(initialName); const [oemNumber, setOemNumber] = useState(""); const [brandName, setBrandName] = useState(""); const [category, setCategory] = useState("عام"); const [buyPrice, setBuyPrice] = useState("0"); const [sellPrice, setSellPrice] = useState(""); const [openingQuantity, setOpeningQuantity] = useState("1"); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  const submit = () => startTransition(async () => { const buy = Number(buyPrice) || 0; const sell = Number(sellPrice) || 0; const result = await createPartAction({ nameAr, oemNumber, brandId: undefined, brandName, categoryId: undefined, category, categoryName: category, chassisIds: [], engineIds: [], chassisCodes: [], engineCodes: [], nameEn: "", brandPartNumber: "", barcode: "", sidePosition: "", binLocationId: undefined, buyPriceLast: buy, sellPriceRetail: sell, sellPriceWholesale: sell, sellPriceMin: sell, openingQuantity: Math.max(0, Math.trunc(Number(openingQuantity) || 0)), minReorderLevel: 2, isActive: true }); if (!result.success) { setError(result.error); return; } const found = await searchPartsForPosAction(result.data.oemNumber); if (!found.success) { setError(found.error); return; } const part = found.data.find((row) => row.id === result.data.id); if (!part) { setError("تم إنشاء الصنف ولكن تعذر تحميله للسلة."); return; } onCreated(part); });
  return <Modal open onClose={onClose} title="إضافة صنف جديد للبيع" description="سيحفظ الصنف في الكتالوج ويضاف مباشرة إلى سلة البيع الحالية." size="md" footer={<><Button variant="ghost" onClick={onClose}>إلغاء</Button><Button loading={pending} onClick={submit} disabled={!nameAr.trim() || !oemNumber.trim() || !brandName.trim() || Number(sellPrice) < 0}>إنشاء وإضافة للسلة</Button></>}><div className="grid gap-3 sm:grid-cols-2">{error ? <div className="sm:col-span-2"><Alert variant="error">{error}</Alert></div> : null}<Field label="اسم الصنف" required><Input autoFocus value={nameAr} onChange={(e) => setNameAr(e.target.value)} /></Field><Field label="OEM" required><Input value={oemNumber} onChange={(e) => setOemNumber(e.target.value)} /></Field><Field label="الماركة" required><Input value={brandName} onChange={(e) => setBrandName(e.target.value)} /></Field><Field label="التصنيف"><Input value={category} onChange={(e) => setCategory(e.target.value)} /></Field><Field label="سعر الشراء"><Input type="number" min={0} value={buyPrice} onChange={(e) => setBuyPrice(e.target.value)} /></Field><Field label="سعر البيع" required><Input type="number" min={0} value={sellPrice} onChange={(e) => setSellPrice(e.target.value)} /></Field><Field label="رصيد افتتاحي"><Input type="number" min={0} value={openingQuantity} onChange={(e) => setOpeningQuantity(e.target.value)} /></Field></div></Modal>;
}
