"use client";

import { useState } from "react";
import { Printer, RefreshCw } from "lucide-react";
import { UniversalDateTimePicker, type DateRangeValue } from "@/components/ui/universal-date-time-picker";
import { Button } from "@/components/ui/button";

const operations = ["بيع", "مرتجع بيع", "شراء", "مرتجع شراء", "قبض", "صرف", "جرد", "تحويل", "تسوية"];
export default function DailyMovementPage() {
  const [tab, setTab] = useState("ملخص"); const [range, setRange] = useState<DateRangeValue>();
  return <main className="space-y-5" dir="rtl"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-white">تقرير الحركة اليومية</h1><p className="text-sm text-bmw-muted">تسوية عمليات المبيعات والمشتريات والخزينة للفترة المحددة.</p></div><div className="flex gap-2"><Button type="button" variant="subtle" onClick={() => window.location.reload()}><RefreshCw size={16}/>تحديث</Button><Button type="button" onClick={() => window.print()}><Printer size={16}/>طباعة</Button></div></header><UniversalDateTimePicker value={range} onChange={setRange}/><div className="flex flex-wrap gap-2">{["ملخص","بيع","مرتجع بيع","شراء","مرتجع شراء"].map((item) => <Button key={item} type="button" variant={tab === item ? "primary" : "subtle"} onClick={() => setTab(item)}>{item}</Button>)}</div>{tab === "ملخص" ? <div className="grid gap-5 xl:grid-cols-2"><section className="bmw-card overflow-hidden"><h2 className="border-b border-bmw-cardBorder p-4 font-bold">مصفوفة العمليات</h2><table className="w-full text-sm"><thead className="bg-bmw-carbon text-bmw-muted"><tr><th className="p-3 text-right">العملية</th><th>العدد</th><th>الإجمالي</th><th>نقدي</th><th>آجل</th></tr></thead><tbody>{operations.map((name) => <tr key={name} className="border-t border-bmw-cardBorder"><td className="p-3">{name}</td><td className="text-center">—</td><td className="text-center">0.00</td><td className="text-center">0.00</td><td className="text-center">0.00</td></tr>)}</tbody></table></section><section className="bmw-card p-4"><h2 className="font-bold">تسوية حركة الخزينة</h2><div className="mt-4 space-y-3">{["رصيد سابق","مبيعات نقدية","مرتجع نقدي","مقبوضات","مدفوعات","صافي الحركة","الرصيد النهائي"].map((name,index) => <div key={name} className={`flex justify-between rounded-lg p-3 ${index > 4 ? "bg-bmw-carbon font-bold" : ""}`}><span>{name}</span><span className={index === 6 ? "text-amber-400" : ""}>0.00 ج.م</span></div>)}</div></section></div> : <section className="bmw-card p-5 text-center text-bmw-muted">ستظهر تفاصيل {tab} للفترة {range?.from || "اليوم"} بعد تحميل التقرير من الخزينة والدفاتر المعتمدة.</section>}</main>;
}
