"use client";

import { useCallback, useEffect, useState } from "react";
import { Printer, RefreshCw } from "lucide-react";
import { UniversalDateTimePicker, type DateRangeValue } from "@/components/ui/universal-date-time-picker";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { getDailyMovementReportAction } from "@/server/actions/reports.actions";

 type ReportData = Extract<Awaited<ReturnType<typeof getDailyMovementReportAction>>, { success: true }>["data"];
const tabs = ["ملخص", "بيع", "مرتجع بيع", "شراء", "مرتجع شراء", "حركات الخزينة"] as const;
type Tab = (typeof tabs)[number];
const initialRange = (): DateRangeValue => { const from = new Date(); from.setHours(0, 0, 0, 0); const iso = (date: Date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); return { from: iso(from), to: iso(new Date()), preset: "TODAY", pinned: false }; };
const money = (amount: number) => `${amount.toLocaleString("ar-EG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ج.م`;

export default function DailyMovementPage() {
  const [tab, setTab] = useState<Tab>("ملخص");
  const [range, setRange] = useState<DateRangeValue>(initialRange);
  const [data, setData] = useState<ReportData | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { if (!range?.from || !range?.to) return; setLoading(true); setError(""); const result = await getDailyMovementReportAction({ fromDate: new Date(range.from), toDate: new Date(range.to), treasuryIds: [] }); if (result.success) setData(result.data); else setError(result.error); setLoading(false); }, [range]);
  useEffect(() => { void load(); }, [load]);
  const invoiceRows = data ? (tab === "بيع" ? data.drillDowns.sales : tab === "مرتجع بيع" ? data.drillDowns.saleReturns : tab === "شراء" ? data.drillDowns.purchases : tab === "مرتجع شراء" ? data.drillDowns.purchaseReturns : []) : [];
  const reconciliation = data?.reconciliation;
  return <main className="space-y-5" dir="rtl">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-white">تقرير الحركة اليومية</h1><p className="text-sm text-bmw-muted">تسوية عمليات المبيعات والمشتريات وحركة الخزائن للفترة المحددة.</p></div><div className="flex gap-2"><Button type="button" variant="subtle" onClick={() => void load()} disabled={loading}><RefreshCw size={16} className={loading ? "animate-spin" : ""} />تحديث</Button><Button type="button" onClick={() => window.print()}><Printer size={16} />طباعة</Button></div></header>
    <UniversalDateTimePicker value={range} onChange={setRange} syncToUrl storageKey="bimmererp:daily-movement-range" />
    <div className="flex flex-wrap gap-2">{tabs.map((item) => <Button key={item} type="button" variant={tab === item ? "primary" : "subtle"} onClick={() => setTab(item)}>{item}</Button>)}</div>
    {error ? <p className="rounded-lg bg-red-950/40 p-3 text-sm text-red-300">{error}</p> : null}
    {tab === "ملخص" ? <div className="grid gap-5 xl:grid-cols-2">
      <section className="bmw-card overflow-hidden"><h2 className="border-b border-bmw-cardBorder p-4 font-bold">مصفوفة العمليات</h2><table className="w-full text-sm"><thead className="bg-bmw-carbon text-bmw-muted"><tr><th className="p-3 text-right">العملية</th><th>العدد</th><th>الإجمالي</th><th>نقدي</th><th>آجل</th></tr></thead><tbody>{data?.operations.map((item) => <tr key={item.key} className="border-t border-bmw-cardBorder"><td className="p-3">{item.label}</td><td className="text-center">{item.count}</td><td className="text-center tabular">{money(item.total)}</td><td className="text-center tabular text-emerald-400">{money(item.paid)}</td><td className="text-center tabular text-amber-400">{money(item.remaining)}</td></tr>) ?? <tr><td colSpan={5} className="p-5 text-center text-bmw-muted">جارٍ تحميل البيانات…</td></tr>}</tbody></table></section>
      <section className="bmw-card p-4"><h2 className="font-bold">تسوية حركة الخزينة</h2><p className="mt-1 text-xs text-bmw-muted">تعتمد القيم النقدية على قيود الخزينة الفعلية لتجنب احتساب تحصيل الفاتورة مرتين.</p><div className="mt-4 space-y-2">{[["تحصيلات مرتبطة بفواتير", reconciliation?.invoiceReceipts], ["سندات قبض مستقلة", reconciliation?.manualReceipts], ["مدفوعات مرتبطة بفواتير", reconciliation?.invoicePayments], ["سندات صرف مستقلة", reconciliation?.manualPayments], ["صافي التحويلات الداخلية", reconciliation?.transferNet], ["صافي حركة الخزينة", reconciliation?.netMovement]].map(([name, value], index) => <div key={String(name)} className={`flex justify-between rounded-lg p-3 ${index === 5 ? "bg-bmw-carbon font-bold" : "bg-bmw-black/20"}`}><span>{name}</span><span className={`tabular ${index === 5 ? "text-amber-400" : "text-white"}`}>{money(Number(value ?? 0))}</span></div>)}</div></section>
    </div> : tab === "حركات الخزينة" ? <section className="bmw-card overflow-x-auto"><table className="w-full text-sm"><thead className="bg-bmw-carbon text-bmw-muted"><tr><th className="p-3 text-right">المرجع</th><th>التاريخ</th><th>التصنيف</th><th>الحساب</th><th>الخزينة</th><th>البيان</th><th>المبلغ</th></tr></thead><tbody>{data?.drillDowns.treasuryMovements.length ? data.drillDowns.treasuryMovements.map((row) => <tr key={`${row.reference}-${row.at}`} className="border-t border-bmw-cardBorder"><td className="p-3 font-mono text-xs font-bold text-bmw-blue">{row.reference}</td><td className="tabular text-center text-xs">{new Date(row.at).toLocaleString("ar-EG")}</td><td><Badge variant={row.amount >= 0 ? "success" : "danger"}>{row.source}</Badge></td><td className="text-center text-xs">{row.account ?? "—"}</td><td className="text-center text-xs">{row.treasury}</td><td className="max-w-[260px] truncate text-xs text-bmw-muted">{row.description}</td><td className="tabular text-center font-bold">{money(Math.abs(row.amount))}</td></tr>) : <tr><td colSpan={7} className="p-6 text-center text-bmw-muted">لا توجد حركات للخزينة للفترة المحددة.</td></tr>}</tbody></table></section> : <section className="bmw-card overflow-x-auto"><table className="w-full text-sm"><thead className="bg-bmw-carbon text-bmw-muted"><tr><th className="p-3 text-right">المرجع</th><th>التاريخ</th><th>الحساب</th><th>الأصناف</th><th>المستخدم</th><th>الخزينة</th><th>الإجمالي</th><th>المدفوع</th><th>المتبقي</th></tr></thead><tbody>{invoiceRows.length ? invoiceRows.map((row) => <tr key={row.id} className="border-t border-bmw-cardBorder"><td className="p-3 font-mono text-xs font-bold text-bmw-blue">{row.reference}</td><td className="tabular whitespace-nowrap text-center text-xs">{new Date(row.at).toLocaleString("ar-EG")}</td><td className="text-center text-xs">{row.account}</td><td className="max-w-[260px] truncate text-xs text-bmw-muted" title={row.itemSummary}>{row.itemSummary || "—"} <span className="text-bmw-blue">({row.itemCount})</span></td><td className="text-center text-xs">{row.user}</td><td className="text-center text-xs">{row.treasury ?? "—"}</td><td className="tabular text-center">{money(row.total)}</td><td className="tabular text-center text-emerald-400">{money(row.paid)}</td><td className="tabular text-center text-amber-400">{money(row.remaining)}</td></tr>) : <tr><td colSpan={9} className="p-6 text-center text-bmw-muted">لا توجد عمليات للفترة المحددة.</td></tr>}</tbody></table></section>}
  </main>;
}
