"use client";

import { useState } from "react";
import { Plus, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

export interface ChassisOption { id: string; code: string; series: string; }
export interface EngineOption { id: string; code: string; displacement: string | null; }
interface FitmentMatrixProps { chassis: ChassisOption[]; engines: EngineOption[]; selectedChassisIds: string[]; selectedEngineIds: string[]; onChangeChassis: (ids: string[]) => void; onChangeEngines: (ids: string[]) => void; selectedChassisCodes: string[]; selectedEngineCodes: string[]; onChangeChassisCodes: (codes: string[]) => void; onChangeEngineCodes: (codes: string[]) => void; }

export function FitmentMatrix({ chassis, engines, selectedChassisIds, selectedEngineIds, onChangeChassis, onChangeEngines, selectedChassisCodes, selectedEngineCodes, onChangeChassisCodes, onChangeEngineCodes }: FitmentMatrixProps) {
  const [chassisInput, setChassisInput] = useState(""); const [engineInput, setEngineInput] = useState("");
  const toggle = (ids: string[], id: string, change: (next: string[]) => void) => change(ids.includes(id) ? ids.filter((value) => value !== id) : [...ids, id]);
  const add = (kind: "chassis" | "engine") => { const raw = kind === "chassis" ? chassisInput : engineInput; const code = raw.trim().toUpperCase(); if (!code) return; const exists = kind === "chassis" ? chassis.some((item) => item.code === code) || selectedChassisCodes.includes(code) : engines.some((item) => item.code === code) || selectedEngineCodes.includes(code); if (!exists) kind === "chassis" ? onChangeChassisCodes([...selectedChassisCodes, code]) : onChangeEngineCodes([...selectedEngineCodes, code]); kind === "chassis" ? setChassisInput("") : setEngineInput(""); };
  const selectedChassis = [...chassis.filter((item) => selectedChassisIds.includes(item.id)).map((item) => item.code), ...selectedChassisCodes];
  const selectedEngines = [...engines.filter((item) => selectedEngineIds.includes(item.id)).map((item) => item.code), ...selectedEngineCodes];
  return <div className="space-y-5" dir="rtl">
    <FitmentSection title="أكواد الشاسيه المتوافقة" selectedLabel="الأكواد المحددة" input={chassisInput} setInput={setChassisInput} placeholder="اكتب كود شاسيه واضغط Enter (مثال: G22, W205, E84)" selected={selectedChassis} onAdd={() => add("chassis")} onRemove={(code) => { const known = chassis.find((item) => item.code === code); if (known) onChangeChassis(selectedChassisIds.filter((id) => id !== known.id)); else onChangeChassisCodes(selectedChassisCodes.filter((item) => item !== code)); }} count={selectedChassis.length}>
      {chassis.map((item) => <button key={item.id} type="button" onClick={() => toggle(selectedChassisIds, item.id, onChangeChassis)} className={cn("rounded-lg border px-2.5 py-1 font-mono text-[11px] font-bold", selectedChassisIds.includes(item.id) ? "border-bmw-blue bg-bmw-blue text-white" : "border-bmw-cardBorder bg-bmw-card text-bmw-muted hover:border-bmw-blue hover:text-white")}>{item.code}</button>)}
    </FitmentSection>
    <FitmentSection title="أكواد المحركات المتوافقة" selectedLabel="المحركات المحددة" input={engineInput} setInput={setEngineInput} placeholder="اكتب كود محرك واضغط Enter (مثال: M274, OM654, N20)" selected={selectedEngines} onAdd={() => add("engine")} onRemove={(code) => { const known = engines.find((item) => item.code === code); if (known) onChangeEngines(selectedEngineIds.filter((id) => id !== known.id)); else onChangeEngineCodes(selectedEngineCodes.filter((item) => item !== code)); }} count={selectedEngines.length}>
      {engines.map((item) => <button key={item.id} type="button" title={item.displacement ?? undefined} onClick={() => toggle(selectedEngineIds, item.id, onChangeEngines)} className={cn("rounded-lg border px-2.5 py-1 font-mono text-[11px] font-bold", selectedEngineIds.includes(item.id) ? "border-emerald-500 bg-emerald-600 text-white" : "border-bmw-cardBorder bg-bmw-card text-bmw-muted hover:border-emerald-500 hover:text-white")}>{item.code}</button>)}
    </FitmentSection>
  </div>;
}
function FitmentSection({ title, selectedLabel, input, setInput, placeholder, selected, onAdd, onRemove, count, children }: { title: string; selectedLabel: string; input: string; setInput: (value: string) => void; placeholder: string; selected: string[]; onAdd: () => void; onRemove: (code: string) => void; count: number; children: React.ReactNode }) { return <section className="space-y-2"><div className="flex items-center justify-between"><p className="text-xs font-bold text-bmw-silver">{title}</p><Badge variant={count ? "blue" : "muted"} mono>{count}</Badge></div><div className="flex gap-2"><Input value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); onAdd(); } }} placeholder={placeholder} className="h-9 text-xs"/><Button type="button" size="sm" variant="outline" onClick={onAdd}><Plus size={14}/>إضافة</Button></div><div className="rounded-xl border border-bmw-cardBorder bg-bmw-carbon p-3"><p className="mb-2 text-[11px] font-bold text-bmw-muted">{selectedLabel}</p><div className="flex min-h-7 flex-wrap gap-1.5">{selected.length ? selected.map((code) => <button key={code} type="button" onClick={() => onRemove(code)} className="rounded-lg border border-bmw-blue bg-bmw-blue/15 px-2 py-1 font-mono text-[11px] text-bmw-blue">{code} <X size={11} className="inline"/></button>) : <span className="text-xs text-bmw-muted">لا توجد أكواد مختارة</span>}</div></div><div className="flex max-h-32 flex-wrap gap-1.5 overflow-y-auto rounded-xl border border-bmw-cardBorder bg-bmw-carbon p-3">{children}</div></section>; }
