"use client";

import { useEffect, useState } from "react";
import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { InventoryMovementPrintTemplate, type InventoryMovementFilters, type InventoryMovementPrintData, type InventoryMovementPrintTab } from "./inventory-movement-print-template";

export function InventoryMovementPrintModal({ data, company, tab, filters, onClose }: { data: InventoryMovementPrintData; company: { name: string; commercialName?: string; logoUrl?: string | null; address?: string; phonePrimary?: string }; tab: InventoryMovementPrintTab; filters: InventoryMovementFilters; onClose: () => void }) {
  const [printing, setPrinting] = useState(false);
  useEffect(() => { if (!printing) return; const complete = () => setPrinting(false); window.addEventListener("afterprint", complete); return () => window.removeEventListener("afterprint", complete); }, [printing]);
  const print = () => { setPrinting(true); requestAnimationFrame(() => { window.setTimeout(async () => { try { await window.document.fonts?.ready; const images = Array.from(window.document.querySelectorAll<HTMLImageElement>("#inventory-movement-print-portal img")); await Promise.all(images.map((image) => image.complete ? Promise.resolve() : new Promise<void>((resolve) => { image.addEventListener("load", () => resolve(), { once: true }); image.addEventListener("error", () => resolve(), { once: true }); }))); window.print(); } finally { window.setTimeout(() => setPrinting(false), 900); } }, 350); }); };
  const css = "@media print { @page { size:A4 portrait; margin:12mm 10mm 15mm 10mm; } body * { visibility:hidden !important; } #inventory-movement-print-portal, #inventory-movement-print-portal * { visibility:visible !important; } #inventory-movement-print-portal { position:fixed !important; inset:0 !important; display:block !important; width:auto !important; min-height:auto !important; height:auto !important; overflow:visible !important; margin:0 !important; background:#fff !important; color:#000 !important; z-index:2147483647 !important; } .inventory-movement-print { box-sizing:border-box !important; font-size:9px !important; } .inventory-movement-print thead { display:table-header-group !important; } .inventory-movement-print tfoot { display:table-footer-group !important; } .inventory-movement-print tr, .inventory-movement-print .print-row { page-break-inside:avoid !important; break-inside:avoid !important; } .inventory-movement-print .summary-metric-cards { page-break-inside:avoid !important; break-inside:avoid !important; } .inventory-movement-print .print-table { width:100% !important; border-collapse:collapse !important; } .inventory-movement-print .print-table th, .inventory-movement-print .print-table td { border:1px solid #94a3b8 !important; padding:3px !important; vertical-align:top !important; } .inventory-movement-print .print-table th { background:#e2e8f0 !important; font-weight:800 !important; } .inventory-movement-print small { display:block !important; color:#475569 !important; font-size:8px !important; } .inventory-movement-print .inventory-print-header { display:flex !important; align-items:flex-start !important; justify-content:space-between !important; gap:12px !important; border-bottom:2px solid #0f172a !important; padding-bottom:8px !important; } .inventory-movement-print .inventory-print-header h1, .inventory-movement-print .inventory-print-header h2 { margin:0 !important; font-size:14px !important; font-weight:900 !important; } .inventory-movement-print .inventory-print-header p, .inventory-movement-print .print-filter-line { color:#475569 !important; font-size:8px !important; } .inventory-movement-print .print-filter-line { display:flex !important; flex-wrap:wrap !important; gap:8px !important; padding:6px 0 !important; } .inventory-movement-print .page-footer { position:fixed !important; bottom:0 !important; left:0 !important; width:100% !important; text-align:center !important; font-size:8px !important; color:#64748b !important; } .inventory-movement-print .page-number::after { content:'صفحة ' counter(page); } }";
  const rowCount = tab === "TOP" ? data.topSelling.length : tab === "DEAD" ? data.deadStock.length : data.ledger.length;
  const document = <InventoryMovementPrintTemplate data={data} company={company} tab={tab} filters={filters}/>;
  return <><style>{css}</style><Modal open onClose={onClose} title="معاينة وطباعة التقرير الكامل" description="سيُطبع كامل سجل التبويب النشط بجميع الصفوف ضمن صفحات A4 متتابعة." size="xl" footer={<><Button variant="ghost" onClick={onClose} disabled={printing}>إغلاق</Button><Button onClick={print} disabled={printing}><Printer size={16}/>{printing ? "يتم تجهيز جميع السجلات…" : "طباعة الآن / حفظ PDF"}</Button></>}><div className="mb-3 flex items-center gap-2 rounded-lg border border-emerald-400/30 bg-emerald-400/10 px-3 py-2 text-xs text-emerald-100"><span className="h-2 w-2 rounded-full bg-emerald-400"/>سيتم طباعة كافة النتائج المصفاة: <strong>{rowCount.toLocaleString("ar-EG")} سجل</strong> (يشمل جميع الصفحات)</div><div className="max-h-[65vh] overflow-auto rounded-xl bg-slate-200 p-4"><div className="mx-auto max-w-[790px] shadow-xl">{document}</div></div></Modal>{printing ? <div id="inventory-movement-print-portal" aria-hidden="true" className="pointer-events-none fixed -left-[10000px] top-0 h-px w-px overflow-hidden opacity-0">{document}</div> : null}</>;
}
