"use client";

import { CURRENCY, formatMoney } from "@/lib/utils";

export type InventoryMovementRow = { id: string; oemNumber: string; nameAr: string; brandName: string; category: string; chassisCodes: string[]; openingStock: number; purchasesIn: number; saleReturnsIn: number; salesOut: number; purchaseReturnsOut: number; adjustments: number; netMovement: number; closingStock: number; unitsSold: number; salesRevenue: number; grossProfit: number | null; grossMargin: number | null; unitCost: number | null; tiedUpCost: number | null; daysSinceLastMovement: number | null; recommendation: string };
export type InventoryMovementPrintData = { canViewCost: boolean; period: { from: string; to: string }; metrics: { unitsSold: number; grossSales: number; inwardUnits: number; frozenCapital: number | null; velocity: number }; topSelling: InventoryMovementRow[]; deadStock: InventoryMovementRow[]; ledger: InventoryMovementRow[] };
export type InventoryMovementPrintTab = "TOP" | "DEAD" | "LEDGER";
export type InventoryMovementFilters = { chassis?: string; category?: string; brand?: string; warehouse?: string };

const titleByTab: Record<InventoryMovementPrintTab, string> = { TOP: "تقرير الأصناف الأكثر مبيعاً وحركة", DEAD: "تقرير الأصناف الراكدة ورأس المال المجمد", LEDGER: "تقرير حركة البضاعة الشاملة" };

function FilterLine({ data, filters, count }: { data: InventoryMovementPrintData; filters: InventoryMovementFilters; count: number }) {
  const selected = [["الشاسيه", filters.chassis], ["التصنيف", filters.category], ["الماركة", filters.brand], ["المخزن", filters.warehouse]].filter((item): item is [string, string] => Boolean(item[1]));
  return <div className="print-filter-line"><span>الفترة: {new Date(data.period.from).toLocaleDateString("ar-EG")} — {new Date(data.period.to).toLocaleDateString("ar-EG")}</span>{selected.length ? selected.map(([label, value]) => <span key={label}>{label}: {value}</span>) : <span>الفلاتر: الكل</span>}<b>إجمالي السجلات: {count.toLocaleString("ar-EG")}</b></div>;
}
function Header({ company, data, filters, tab, count }: { company: { name: string; commercialName?: string; logoUrl?: string | null; address?: string; phonePrimary?: string }; data: InventoryMovementPrintData; filters: InventoryMovementFilters; tab: InventoryMovementPrintTab; count: number }) {
  return <><header className="inventory-print-header"><div className="flex items-center gap-3">{company.logoUrl ? <img src={company.logoUrl} alt="" className="h-11 w-auto object-contain"/> : null}<div><h1>{company.name}</h1><p>{company.commercialName || "BimmerERP"}</p></div></div><div className="text-left"><h2>{titleByTab[tab]}</h2><p>تقرير تحليلي للمخزون والسيولة التشغيلية</p></div></header><FilterLine data={data} filters={filters} count={count}/></>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded border border-slate-300 bg-slate-50 p-2"><p className="text-[10px] text-slate-600">{label}</p><b className="mt-1 block text-sm">{value}</b></div>; }
function PrintTable({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className="w-full overflow-hidden print:overflow-visible"><table className={`print-table table-fixed w-full border-collapse text-right ${className}`}>{children}</table></div>; }

export function InventoryMovementPrintTemplate({ data, company, tab, filters }: { data: InventoryMovementPrintData; company: { name: string; commercialName?: string; logoUrl?: string | null; address?: string; phonePrimary?: string }; tab: InventoryMovementPrintTab; filters: InventoryMovementFilters }) {
  const rows = tab === "TOP" ? data.topSelling : tab === "DEAD" ? data.deadStock : data.ledger;
  return <article className="inventory-movement-print bg-white p-5 text-slate-900" dir="rtl"><Header company={company} data={data} filters={filters} tab={tab} count={rows.length}/>{tab === "TOP" ? <><section className="summary-metric-cards my-3 grid grid-cols-3 gap-2"><Metric label="إجمالي القطع المباعة" value={`${data.metrics.unitsSold.toLocaleString("ar-EG")} قطعة`}/><Metric label="قيمة المبيعات" value={`${formatMoney(data.metrics.grossSales)} ${CURRENCY}`}/><Metric label="معدل دوران المخزون" value={`${data.metrics.velocity.toFixed(2)}×`}/></section><TopLedger rows={rows} canViewCost={data.canViewCost}/></> : tab === "DEAD" ? <><section className="summary-metric-cards my-3 grid grid-cols-2 gap-2"><Metric label="عدد الأصناف الراكدة" value={`${rows.length.toLocaleString("ar-EG")} صنف`}/><Metric label="إجمالي رأس المال المجمد" value={data.metrics.frozenCapital === null ? "غير مصرح" : `${formatMoney(data.metrics.frozenCapital)} ${CURRENCY}`}/></section><DeadLedger rows={rows} canViewCost={data.canViewCost}/></> : <FullLedger rows={rows}/>}<footer className="page-footer">تم إنشاء التقرير من BimmerERP — <span className="page-number"/></footer></article>;
}

function TopLedger({ rows, canViewCost }: { rows: InventoryMovementRow[]; canViewCost: boolean }) {
  return <PrintTable className="inventory-top-table"><colgroup>{canViewCost ? <><col className="w-[4%]"/><col className="w-[15%]"/><col className="w-[21%]"/><col className="w-[15%]"/><col className="w-[8%]"/><col className="w-[12%]"/><col className="w-[11%]"/><col className="w-[6%]"/><col className="w-[8%]"/></> : <><col className="w-[5%]"/><col className="w-[18%]"/><col className="w-[25%]"/><col className="w-[18%]"/><col className="w-[10%]"/><col className="w-[15%]"/><col className="w-[9%]"/></>}</colgroup><thead><tr><th>#</th><th>رقم OEM</th><th>اسم القطعة</th><th>الماركة والتوافق</th><th>الكمية المباعة</th><th>إجمالي الإيراد</th>{canViewCost ? <><th>الربح المحقق</th><th>الهامش</th></> : null}<th>الرصيد الحالي</th></tr></thead><tbody>{rows.map((row, index) => <tr className="print-row" key={row.id}><td className="text-center font-mono whitespace-nowrap">{index + 1}</td><td className="font-mono font-bold whitespace-nowrap overflow-hidden text-ellipsis" dir="ltr">{row.oemNumber}</td><td className="font-semibold leading-snug break-words">{row.nameAr}</td><td className="overflow-hidden text-ellipsis whitespace-nowrap">{row.brandName}<small>{row.chassisCodes.join("، ") || "—"}</small></td><td className="text-center font-bold whitespace-nowrap">{row.unitsSold}</td><td className="text-left font-mono font-semibold whitespace-nowrap" dir="ltr">{formatMoney(row.salesRevenue)}</td>{canViewCost ? <><td className="text-left font-mono font-semibold whitespace-nowrap" dir="ltr">{formatMoney(row.grossProfit ?? 0)}</td><td className="text-center font-mono whitespace-nowrap" dir="ltr">{(row.grossMargin ?? 0).toFixed(1)}%</td></> : null}<td className="text-center font-bold whitespace-nowrap">{row.closingStock}</td></tr>)}</tbody></PrintTable>;
}

function DeadLedger({ rows, canViewCost }: { rows: InventoryMovementRow[]; canViewCost: boolean }) {
  return <PrintTable className="inventory-dead-table"><colgroup>{canViewCost ? <><col className="w-[4%]"/><col className="w-[15%]"/><col className="w-[22%]"/><col className="w-[13%]"/><col className="w-[7%]"/><col className="w-[11%]"/><col className="w-[13%]"/><col className="w-[7%]"/><col className="w-[8%]"/></> : <><col className="w-[5%]"/><col className="w-[18%]"/><col className="w-[26%]"/><col className="w-[18%]"/><col className="w-[12%]"/><col className="w-[10%]"/><col className="w-[11%]"/></>}</colgroup><thead><tr><th>#</th><th>رقم OEM</th><th>اسم القطعة</th><th>الماركة / التصنيف</th><th>الرصيد الراكد</th>{canViewCost ? <><th>تكلفة الوحدة</th><th>رأس المال المجمد</th></> : null}<th>آخر حركة</th><th>الإجراء المقترح</th></tr></thead><tbody>{rows.map((row, index) => <tr className="print-row" key={row.id}><td className="text-center font-mono whitespace-nowrap">{index + 1}</td><td className="font-mono font-bold whitespace-nowrap overflow-hidden text-ellipsis" dir="ltr">{row.oemNumber}</td><td className="font-semibold leading-snug break-words">{row.nameAr}</td><td className="overflow-hidden text-ellipsis whitespace-nowrap"><span>{row.brandName}</span><small>{row.category}</small></td><td className="text-center font-bold whitespace-nowrap">{row.closingStock}</td>{canViewCost ? <><td className="text-left font-mono font-semibold whitespace-nowrap" dir="ltr">{row.unitCost === null ? "—" : formatMoney(row.unitCost)}</td><td className="text-left font-mono font-black whitespace-nowrap" dir="ltr">{row.tiedUpCost === null ? "—" : `${formatMoney(row.tiedUpCost)} ${CURRENCY}`}</td></> : null}<td className="text-center whitespace-nowrap">{row.daysSinceLastMovement === null ? "—" : `${row.daysSinceLastMovement} يوم`}</td><td className="text-center"><span className="inline-block max-w-full overflow-hidden text-ellipsis whitespace-nowrap rounded border border-slate-300 bg-slate-100 px-1 py-0.5 text-[8px] font-medium text-slate-800">{row.recommendation || "عرض ترويجي"}</span></td></tr>)}</tbody></PrintTable>;
}

function FullLedger({ rows }: { rows: InventoryMovementRow[] }) {
  return <PrintTable className="inventory-full-table dense"><colgroup><col className="w-[4%]"/><col className="w-[14%]"/><col className="w-[25%]"/><col className="w-[8%]"/><col className="w-[8%]"/><col className="w-[8%]"/><col className="w-[8%]"/><col className="w-[8%]"/><col className="w-[8%]"/><col className="w-[9%]"/></colgroup><thead><tr><th>#</th><th>OEM</th><th>اسم القطعة</th><th>رصيد البداية</th><th>وارد مشتريات</th><th>وارد مرتجع</th><th>منصرف مبيعات</th><th>منصرف مرتجع</th><th>تسويات</th><th>رصيد النهاية</th></tr></thead><tbody>{rows.map((row, index) => <tr className="print-row" key={row.id}><td className="text-center font-mono whitespace-nowrap">{index + 1}</td><td className="font-mono font-bold whitespace-nowrap overflow-hidden text-ellipsis" dir="ltr">{row.oemNumber}</td><td className="font-semibold leading-snug break-words">{row.nameAr}<small>{row.brandName}</small></td><td className="text-center font-mono whitespace-nowrap">{row.openingStock}</td><td className="text-center font-mono whitespace-nowrap">+{row.purchasesIn}</td><td className="text-center font-mono whitespace-nowrap">+{row.saleReturnsIn}</td><td className="text-center font-mono whitespace-nowrap">−{row.salesOut}</td><td className="text-center font-mono whitespace-nowrap">−{row.purchaseReturnsOut}</td><td className="text-center font-mono whitespace-nowrap">{row.adjustments}</td><td className="text-center font-mono font-bold whitespace-nowrap">{row.closingStock}</td></tr>)}</tbody></PrintTable>;
}
