import { formatDateTime, formatMoney, ARABIC_LABELS } from "@/lib/utils";
import type { InvoicePrintData } from "@/lib/invoice-print-types";
import { InvoiceQrCode } from "../qr-code";

export function ClassicInvoiceTemplate({ data, showBalance = true, showPartMeta = true }: { data: InvoicePrintData; showBalance?: boolean; showPartMeta?: boolean }) {
  const party = data.invoice.type === "PURCHASE" || data.invoice.type === "PURCHASE_RETURN" ? "المورد" : "العميل";
  const title = data.invoice.type === "PURCHASE" ? "فاتورة مشتريات" : data.invoice.type === "SALE_RETURN" ? "مرتجع مبيعات" : data.invoice.type === "PURCHASE_RETURN" ? "مرتجع مشتريات" : "فاتورة مبيعات";
  return <article id="printable-area" className="invoice-print-page invoice-a4 classic-invoice-print" dir="rtl">
    {data.invoice.isVoided ? <div className="invoice-void-watermark">ملغاة</div> : null}
    <header className="grid grid-cols-[1fr_220px] border-2 border-black text-black"><div className="border-l-2 border-black p-4"><div className="flex items-start gap-3">{data.company.logoUrl ? <img src={data.company.logoUrl} alt="شعار المنشأة" className="h-14 w-14 object-contain" /> : null}<div><h1 className="text-xl font-black">{data.company.name}</h1><p className="font-bold">{data.company.commercialName}</p><p className="text-xs">{data.company.address}</p><p className="text-xs">هاتف: {[data.company.phonePrimary, data.company.phoneSecondary].filter(Boolean).join(" - ") || "—"}</p><p className="text-xs">ضريبي: {data.company.taxNumber || "—"} • س.ت: {data.company.commercialRegister || "—"}</p></div></div></div><div className="p-4 text-center"><h2 className="text-lg font-black">{title}</h2><p className="mt-2 border-y border-black py-1 font-mono text-sm" dir="ltr">{data.invoice.invoiceNumber}</p><p className="mt-2 text-xs">{formatDateTime(data.invoice.createdAt)}</p><p className="text-xs">{ARABIC_LABELS.paymentMethod[data.invoice.paymentMethod as keyof typeof ARABIC_LABELS.paymentMethod] ?? data.invoice.paymentMethod}</p></div></header>
    <section className="mt-3 grid grid-cols-2 gap-3 text-xs text-black"><div className="border-2 border-black p-3"><h3 className="mb-2 border-b border-black pb-1 font-black">بيانات {party}</h3><p><b>الاسم:</b> {data.account.name}</p><p><b>الكود:</b> {data.account.accountNumber}</p><p><b>الهاتف:</b> {data.account.phone || "—"}</p><p><b>الرقم الضريبي:</b> {data.account.taxNumber || "—"}</p></div><div className="border-2 border-black p-3"><h3 className="mb-2 border-b border-black pb-1 font-black">بيانات العملية</h3><p><b>المستخدم:</b> {data.invoice.cashierName || "—"}</p><p><b>الخزينة:</b> {data.invoice.treasuryName || "—"}</p><p><b>السيارة:</b> {data.account.vehicleLabel || "—"}</p><p><b>مرجع المصدر:</b> {data.invoice.sourceInvoiceNumber || "—"}</p></div></section>
    <table className="mt-3 w-full border-collapse border-2 border-black text-xs text-black"><thead><tr className="bg-slate-100"><th className="border border-black p-2">م</th><th className="border border-black p-2">اسم الصنف</th>{showPartMeta ? <><th className="border border-black p-2">OEM</th><th className="border border-black p-2">الماركة</th></> : null}<th className="border border-black p-2">الكمية</th><th className="border border-black p-2">السعر</th><th className="border border-black p-2">الخصم</th><th className="border border-black p-2">الإجمالي</th></tr></thead><tbody>{data.lines.map((line, index) => <tr key={line.id}><td className="border border-black p-2 text-center">{index + 1}</td><td className="border border-black p-2 font-bold">{line.nameAr}</td>{showPartMeta ? <><td className="border border-black p-2 font-mono" dir="ltr">{line.oemNumber}</td><td className="border border-black p-2">{line.brandName}</td></> : null}<td className="border border-black p-2 text-center">{line.quantity}</td><td className="border border-black p-2 text-left" dir="ltr">{formatMoney(line.unitPrice)}</td><td className="border border-black p-2 text-left" dir="ltr">{formatMoney(line.lineDiscount)}</td><td className="border border-black p-2 text-left font-black" dir="ltr">{formatMoney(line.totalPrice)}</td></tr>)}</tbody></table>
    <section className="mt-3 grid grid-cols-[1fr_280px] gap-3 text-xs text-black"><div className="border-2 border-black p-3"><p className="font-black">ملاحظات وشروط الضمان والاسترجاع</p><p className="mt-2 min-h-12 whitespace-pre-line">{data.invoice.notes || data.company.footer || "لا يتم قبول الاسترجاع إلا وفق سياسة المنشأة المعتمدة."}</p><div className="mt-8 flex justify-between border-t border-black pt-2"><span>توقيع العميل: __________________</span><span>توقيع البائع: __________________</span></div></div><div className="border-2 border-black"><p className="flex justify-between border-b border-black p-2"><span>الإجمالي قبل الخصم</span><b>{formatMoney(data.invoice.subtotal)}</b></p><p className="flex justify-between border-b border-black p-2"><span>الخصم</span><b>{formatMoney(data.invoice.discountAmount)}</b></p><p className="flex justify-between border-b border-black p-2"><span>الضريبة</span><b>{formatMoney(data.invoice.taxAmount)}</b></p><p className="flex justify-between border-b-2 border-black bg-slate-100 p-2 text-sm font-black"><span>إجمالي الفاتورة</span><b>{formatMoney(data.invoice.grandTotal)}</b></p><p className="flex justify-between border-b border-black p-2"><span>المدفوع</span><b>{formatMoney(data.invoice.paidAmount)}</b></p><p className="flex justify-between p-2"><span>المتبقي</span><b>{formatMoney(data.invoice.remainingAmount)}</b></p>{showBalance ? <div className="border-t-2 border-black p-2"><p className="flex justify-between"><span>الرصيد السابق</span><b>{formatMoney(data.invoice.accountBalanceBefore ?? 0)}</b></p><p className="mt-1 flex justify-between"><span>الرصيد الحالي</span><b>{formatMoney(data.invoice.accountBalanceAfter ?? data.invoice.remainingAmount)}</b></p></div> : null}</div></section>
    <footer className="mt-3 flex items-end justify-between border-t-2 border-black pt-2 text-[10px] text-black"><span>{data.company.footer || "شكراً لتعاملكم معنا"}</span><span className="flex items-center gap-2"><InvoiceQrCode value={data.invoice.qrPayload} /><span className="font-mono" dir="ltr">{data.invoice.invoiceNumber}</span></span></footer>
  </article>;
}
