import { ARABIC_LABELS, CURRENCY, formatDateTime, formatMoney } from "@/lib/utils";
import type { UniversalPrintOptions } from "@/components/print/universal-print-types";
import type { InvoiceListRow } from "@/server/services/invoices.service";

type Company = { name: string; commercialName?: string; address?: string; phone?: string; phonePrimary?: string; taxNumber?: string; logoUrl?: string | null };

export function FilteredInvoiceListPrintDocument({ rows, company, filters, options }: { rows: InvoiceListRow[]; company: Company; filters: { query: string; type: string; status: string; includeVoided: boolean }; options: UniversalPrintOptions }) {
  const totals = rows.reduce((sum, row) => ({ grand: sum.grand + row.grandTotal, paid: sum.paid + row.paidAmount, remaining: sum.remaining + row.remainingAmount }), { grand: 0, paid: 0, remaining: 0 });
  const applied = [filters.query ? `بحث: ${filters.query}` : "", filters.type === "SALE" ? "مبيعات" : filters.type === "PURCHASE" ? "مشتريات" : "", filters.status ? `الحالة: ${ARABIC_LABELS.paymentStatus[filters.status as keyof typeof ARABIC_LABELS.paymentStatus] ?? filters.status}` : "", filters.includeVoided ? "يشمل الملغاة" : ""].filter(Boolean).join(" | ") || "كل الفواتير";
  return <article className={`universal-document universal-invoice-register ${options.template}`} dir="rtl"><header className="universal-document-header"><div className="flex items-center gap-3">{company.logoUrl ? <img src={company.logoUrl} alt="" className="h-12 max-w-20 object-contain"/> : null}<div><h1>{company.name}</h1><p>{company.commercialName ?? "سجل الفواتير"}</p>{company.address ? <p>{company.address}</p> : null}</div></div><div className="text-left"><h2>سجل الفواتير المصفّى</h2><p>تاريخ الطباعة: {formatDateTime(new Date().toISOString())}</p>{company.taxNumber ? <p dir="ltr">TAX: {company.taxNumber}</p> : null}</div></header><section className="my-3 rounded border border-slate-300 bg-slate-50 px-3 py-2 text-xs"><b>الفلاتر المطبقة:</b> {applied} <span className="mx-1">•</span> <b>إجمالي السجلات: {rows.length.toLocaleString("ar-EG")}</b></section><section className="mb-3 grid grid-cols-3 gap-2"><Metric label="إجمالي الفواتير" value={`${formatMoney(totals.grand)} ${CURRENCY}`}/><Metric label="إجمالي المدفوع" value={`${formatMoney(totals.paid)} ${CURRENCY}`}/><Metric label="إجمالي المتبقي" value={`${formatMoney(totals.remaining)} ${CURRENCY}`}/></section><table className="print-table"><thead><tr><th>#</th><th>رقم الفاتورة</th><th>النوع</th><th>الحساب</th><th>الأصناف</th><th>الإجمالي</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th><th>المستخدم</th><th>التاريخ</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.id} className={row.isVoided ? "opacity-50" : undefined}><td>{index + 1}</td><td dir="ltr">{row.invoiceNumber}</td><td>{ARABIC_LABELS.invoiceType[row.type]}</td><td>{row.accountName}</td><td>{row.itemCount}</td><td dir="ltr">{formatMoney(row.grandTotal)}</td><td dir="ltr">{formatMoney(row.paidAmount)}</td><td dir="ltr">{formatMoney(row.remainingAmount)}</td><td>{row.isVoided ? "ملغاة" : ARABIC_LABELS.paymentStatus[row.paymentStatus]}</td><td>{row.userName}</td><td>{formatDateTime(row.createdAt)}</td></tr>)}</tbody><tfoot><tr><th colSpan={5}>الإجماليات</th><th dir="ltr">{formatMoney(totals.grand)}</th><th dir="ltr">{formatMoney(totals.paid)}</th><th dir="ltr">{formatMoney(totals.remaining)}</th><th colSpan={3}/></tr></tfoot></table></article>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded border border-slate-300 p-2 text-center"><p className="text-[11px] text-slate-500">{label}</p><b className="tabular text-sm">{value}</b></div>; }
