import { formatDateTime, formatMoney, ARABIC_LABELS } from "@/lib/utils";
import type { InvoicePrintData } from "@/lib/invoice-print-types";
import { InvoiceQrCode } from "../qr-code";

function documentLabel(type: string) {
  return type === "PURCHASE" ? "فاتورة مشتريات" : type === "SALE_RETURN" ? "إشعار دائن / مرتجع مبيعات" : type === "PURCHASE_RETURN" ? "إشعار مدين / مرتجع مشتريات" : "فاتورة مبيعات";
}

export function ModernInvoiceTemplate({ data, showBalance = true, showPartMeta = true }: { data: InvoicePrintData; showBalance?: boolean; showPartMeta?: boolean }) {
  const party = data.invoice.type === "PURCHASE" || data.invoice.type === "PURCHASE_RETURN" ? "المورد" : "العميل";
  return <article id="printable-area" className="invoice-print-page invoice-a4 modern-invoice-print" dir="rtl">
    {data.invoice.isVoided ? <div className="invoice-void-watermark">ملغاة</div> : null}
    <header className="mb-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="h-2 bg-gradient-to-l from-[#0066b3] via-[#6c7c92] to-[#e53935]" />
      <div className="flex items-start justify-between gap-5 p-5">
        <div className="flex items-start gap-3"><div className="flex h-16 w-16 items-center justify-center overflow-hidden rounded-xl border border-slate-200 bg-slate-50">{data.company.logoUrl ? <img src={data.company.logoUrl} alt="شعار المنشأة" className="h-full w-full object-contain" /> : <span className="text-xl font-black text-[#0066b3]">B</span>}</div><div><h1 className="text-xl font-black text-slate-900">{data.company.name}</h1><p className="text-sm font-medium text-slate-500">{data.company.commercialName}</p><p className="mt-1 text-[11px] text-slate-500">{data.company.address} • {[data.company.phonePrimary, data.company.phoneSecondary].filter(Boolean).join(" - ")}</p><p className="text-[11px] text-slate-500">ضريبي: {data.company.taxNumber || "—"} • سجل: {data.company.commercialRegister || "—"}</p></div></div>
        <div className="rounded-xl bg-slate-900 px-4 py-3 text-left text-white"><p className="text-xs text-slate-300">{documentLabel(data.invoice.type)}</p><h2 className="font-mono text-lg font-bold" dir="ltr">{data.invoice.invoiceNumber}</h2><p className="text-xs text-slate-300">{formatDateTime(data.invoice.createdAt)}</p></div>
      </div>
    </header>
    <section className="mb-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-slate-200 bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">بيانات {party}</p><p className="mt-1 font-bold text-slate-900">{data.account.name} <span className="font-mono text-xs text-slate-500">({data.account.accountNumber})</span></p><p className="text-xs text-slate-500">{data.account.phone || "لا يوجد هاتف"}{data.account.vehicleLabel ? ` • ${data.account.vehicleLabel}` : ""}</p></div><div className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">بيانات التشغيل</p><p className="mt-1 text-sm text-slate-800">الكاشير: <b>{data.invoice.cashierName || "—"}</b> • الخزينة: <b>{data.invoice.treasuryName || "—"}</b></p><p className="text-xs text-slate-500">طريقة الدفع: {ARABIC_LABELS.paymentMethod[data.invoice.paymentMethod as keyof typeof ARABIC_LABELS.paymentMethod] ?? data.invoice.paymentMethod}</p></div></section>
    <table className="w-full overflow-hidden rounded-xl border border-slate-200 text-right text-xs"><thead className="bg-slate-900 text-white"><tr><th className="p-2 text-center">#</th><th className="p-2">الصنف</th>{showPartMeta ? <><th className="p-2">OEM / الماركة</th></> : null}<th className="p-2 text-center">الكمية</th><th className="p-2 text-left">سعر الوحدة</th><th className="p-2 text-left">الخصم</th><th className="p-2 text-left">الإجمالي</th></tr></thead><tbody>{data.lines.map((line, index) => <tr key={line.id} className={index % 2 ? "bg-slate-50" : "bg-white"}><td className="p-2 text-center text-slate-500">{index + 1}</td><td className="p-2 font-semibold text-slate-900">{line.nameAr}</td>{showPartMeta ? <td className="p-2"><span className="rounded bg-blue-50 px-1.5 py-0.5 font-mono text-[10px] text-blue-700" dir="ltr">{line.oemNumber}</span><span className="mr-1 rounded bg-slate-100 px-1.5 py-0.5 text-[10px] text-slate-600">{line.brandName}</span></td> : null}<td className="p-2 text-center">{line.quantity}</td><td className="p-2 text-left tabular" dir="ltr">{formatMoney(line.unitPrice)}</td><td className="p-2 text-left tabular text-rose-600" dir="ltr">{formatMoney(line.lineDiscount)}</td><td className="p-2 text-left font-bold tabular" dir="ltr">{formatMoney(line.totalPrice)}</td></tr>)}</tbody></table>
    <section className="mt-4 grid grid-cols-[1fr_250px] gap-4"><div className="rounded-xl border border-slate-200 p-3 text-xs text-slate-600"><p className="font-bold text-slate-900">ملاحظات وشروط</p><p className="mt-1 whitespace-pre-line">{data.invoice.notes || data.company.footer || "شكراً لتعاملكم معنا. تطبق سياسة الضمان والاستبدال المعتمدة لدى المنشأة."}</p><div className="mt-8 flex justify-between border-t border-slate-200 pt-3 text-slate-700"><span>توقيع المستلم: __________________</span><span>المخول بالبيع: __________________</span></div></div><div className="space-y-2 rounded-xl bg-slate-900 p-3 text-xs text-white"><p className="flex justify-between text-slate-300"><span>قبل الخصم</span><b>{formatMoney(data.invoice.subtotal)}</b></p><p className="flex justify-between text-rose-300"><span>الخصم</span><b>{formatMoney(data.invoice.discountAmount)}</b></p><p className="flex justify-between text-slate-300"><span>الضريبة</span><b>{formatMoney(data.invoice.taxAmount)}</b></p><p className="flex justify-between border-y border-slate-600 py-2 text-base"><span>الإجمالي</span><b>{formatMoney(data.invoice.grandTotal)}</b></p><p className="flex justify-between text-emerald-300"><span>المدفوع</span><b>{formatMoney(data.invoice.paidAmount)}</b></p><p className="flex justify-between text-amber-300"><span>المتبقي</span><b>{formatMoney(data.invoice.remainingAmount)}</b></p>{showBalance ? <div className="mt-2 rounded bg-white/10 p-2 text-[11px]"><p className="flex justify-between"><span>الرصيد السابق</span><b>{formatMoney(data.invoice.accountBalanceBefore ?? 0)}</b></p><p className="mt-1 flex justify-between"><span>الرصيد الحالي</span><b>{formatMoney(data.invoice.accountBalanceAfter ?? data.invoice.remainingAmount)}</b></p></div> : null}</div></section>
    <footer className="mt-4 flex items-center justify-between border-t border-slate-200 pt-3 text-[10px] text-slate-500"><span>{data.company.footer || "شكراً لثقتكم بنا"}</span><span className="flex items-center gap-2"><InvoiceQrCode value={data.invoice.qrPayload} /><span className="font-mono" dir="ltr">{data.invoice.invoiceNumber}</span></span></footer>
  </article>;
}
