"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Ban, Download, FileText, Pencil, Printer, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Alert, Modal } from "@/components/ui/modal";
import { Field, Input, Select, Textarea } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { EmptyState, TBody, TD, TH, THead, TR, Table } from "@/components/ui/table";
import { ARABIC_LABELS, CURRENCY, formatDateTime, formatMoney, formatOemNumber } from "@/lib/utils";
import { getInvoiceDetailAction } from "@/server/actions/invoices.read.actions";
import { voidInvoiceAction } from "@/server/actions/invoice.actions";
import type { InvoiceDetail } from "@/server/services/invoices.service";

type LedgerRow = { id: string; reason: keyof typeof ARABIC_LABELS.stockReason; quantityDelta: number; balanceAfter: number; unitCost: number; unitSalePrice: number | null; totalSalePrice: number | null; invoiceUnitCost: number | null; invoiceTotalCost: number | null; binCode: string | null; performedBy: string; invoiceId: string | null; invoiceNumber: string | null; invoiceType: string | null; partyName: string | null; note: string | null; createdAt: string };

export function PartLedgerClient({ part, rows, canVoid }: { part: { id: string; nameAr: string; oemNumber: string; stockQuantity: number }; rows: LedgerRow[]; canVoid: boolean }) {
  const router = useRouter();
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [reason, setReason] = useState("ALL");
  const [bin, setBin] = useState("ALL");
  const [printRequested, setPrintRequested] = useState(false);
  const [invoiceTarget, setInvoiceTarget] = useState<{ id: string; number: string } | null>(null);
  const bins = useMemo(() => Array.from(new Set(rows.map((row) => row.binCode).filter((value): value is string => Boolean(value)))).sort(), [rows]);
  const filtered = useMemo(() => rows.filter((row) => {
    const at = new Date(row.createdAt).getTime();
    return (!from || at >= new Date(`${from}T00:00:00`).getTime()) && (!to || at <= new Date(`${to}T23:59:59.999`).getTime()) && (reason === "ALL" || row.reason === reason) && (bin === "ALL" || row.binCode === bin);
  }), [rows, from, to, reason, bin]);
  const totals = useMemo(() => filtered.reduce((sum, row) => ({ inbound: sum.inbound + Math.max(0, row.quantityDelta), outbound: sum.outbound + Math.abs(Math.min(0, row.quantityDelta)), cost: sum.cost + Math.abs(row.quantityDelta) * row.unitCost, sales: sum.sales + (row.totalSalePrice ?? 0) }), { inbound: 0, outbound: 0, cost: 0, sales: 0 }), [filtered]);
  useEffect(() => { if (!printRequested) return; const done = () => setPrintRequested(false); window.addEventListener("afterprint", done); const timer = window.setTimeout(() => window.print(), 60); return () => { window.clearTimeout(timer); window.removeEventListener("afterprint", done); }; }, [printRequested]);
  const exportCsv = () => { const output = [["التاريخ", "الحركة", "المخزن", "وارد", "صادر", "الرصيد", "سعر البيع", "إجمالي البيع", "التكلفة", "إجمالي التكلفة", "الفاتورة", "الحساب", "البيان"], ...filtered.map((row) => [formatDateTime(row.createdAt), ARABIC_LABELS.stockReason[row.reason], row.binCode ?? "", String(Math.max(0, row.quantityDelta)), String(Math.abs(Math.min(0, row.quantityDelta))), String(row.balanceAfter), String(row.unitSalePrice ?? ""), String(row.totalSalePrice ?? ""), String(row.unitCost), String(Math.abs(row.quantityDelta) * row.unitCost), row.invoiceNumber ?? "", row.partyName ?? "", row.note ?? ""])]; const csv = `\uFEFF${output.map((line) => line.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\n")}`; const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `دفتر-حركة-${part.oemNumber}.csv`; link.click(); URL.revokeObjectURL(url); };
  return <main className="space-y-4" dir="rtl">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-bold text-white">دفتر حركة الصنف التفصيلي</h1><p className="text-sm text-bmw-muted">{part.nameAr} — <span className="font-mono">{part.oemNumber}</span></p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setPrintRequested(true)}><Printer size={15} /> طباعة A4</Button><Button variant="outline" onClick={exportCsv}><Download size={15} /> تصدير CSV</Button><Button variant="ghost" onClick={() => router.push("/inventory")}><X size={15} /> إغلاق</Button></div></header>
    <section className="bmw-card grid gap-3 p-4 md:grid-cols-4"><div>الرصيد الحالي: <b>{part.stockQuantity}</b></div><div>إجمالي الوارد: <b className="text-emerald-400">{totals.inbound}</b></div><div>إجمالي الصادر: <b className="text-bmw-mRed">{totals.outbound}</b></div><div>قيمة التكلفة: <b>{formatMoney(totals.cost)} {CURRENCY}</b></div></section>
    <section className="bmw-card grid gap-3 p-4 md:grid-cols-4"><Field label="من"><Input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></Field><Field label="إلى"><Input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></Field><Field label="نوع الحركة"><Select value={reason} onChange={(event) => setReason(event.target.value)}><option value="ALL">كل الحركات</option><option value="PURCHASE">شراء</option><option value="SALE">بيع</option><option value="SALE_RETURN">مرتجع بيع</option><option value="PURCHASE_RETURN">مرتجع شراء</option><option value="MANUAL_ADJUSTMENT">تسوية</option><option value="OPENING_BALANCE">رصيد افتتاحي</option><option value="STOCKTAKE">جرد</option></Select></Field><Field label="المخزن / موقع الرف"><Select value={bin} onChange={(event) => setBin(event.target.value)}><option value="ALL">كل المواقع</option>{bins.map((value) => <option key={value} value={value}>{value}</option>)}</Select></Field></section>
    <section className="bmw-card overflow-x-auto"><Table><THead><TR><TH>التاريخ</TH><TH>الحركة</TH><TH>الموقع</TH><TH>وارد</TH><TH>صادر</TH><TH>الرصيد</TH><TH>سعر البيع</TH><TH>إجمالي البيع</TH><TH>سعر الشراء</TH><TH>إجمالي التكلفة</TH><TH>الفاتورة</TH><TH>الحساب</TH><TH>البيان</TH></TR></THead><TBody>{filtered.length === 0 ? <EmptyState colSpan={13} title="لا توجد حركات وفق الفلاتر" /> : filtered.map((row) => <TR key={row.id}><TD className="tabular whitespace-nowrap text-xs text-bmw-muted">{formatDateTime(row.createdAt)}</TD><TD><Badge variant={row.quantityDelta > 0 ? "success" : row.quantityDelta < 0 ? "danger" : "muted"}>{ARABIC_LABELS.stockReason[row.reason]}</Badge></TD><TD className="font-mono text-xs">{row.binCode ?? "—"}</TD><TD className="tabular text-emerald-400">{row.quantityDelta > 0 ? row.quantityDelta : "—"}</TD><TD className="tabular text-bmw-mRed">{row.quantityDelta < 0 ? Math.abs(row.quantityDelta) : "—"}</TD><TD><span className="rounded-full bg-bmw-blue/15 px-2 py-1 font-mono text-xs font-bold text-bmw-blue">{row.balanceAfter}</span></TD><TD className="tabular">{row.unitSalePrice !== null ? formatMoney(row.unitSalePrice) : "—"}</TD><TD className="tabular">{row.totalSalePrice !== null ? formatMoney(row.totalSalePrice) : "—"}</TD><TD className="tabular">{row.invoiceUnitCost !== null ? formatMoney(row.invoiceUnitCost) : row.unitCost ? formatMoney(row.unitCost) : "—"}</TD><TD className="tabular">{row.invoiceTotalCost !== null ? formatMoney(row.invoiceTotalCost) : row.unitCost ? formatMoney(Math.abs(row.quantityDelta) * row.unitCost) : "—"}</TD><TD>{row.invoiceNumber ? <button type="button" className="font-mono text-xs font-bold text-bmw-blue hover:underline" onClick={() => row.invoiceId && setInvoiceTarget({ id: row.invoiceId, number: row.invoiceNumber! })}><FileText className="ml-1 inline" size={13} />{row.invoiceNumber}</button> : "—"}</TD><TD className="max-w-[150px] truncate text-xs">{row.partyName ?? "—"}</TD><TD className="max-w-[180px] truncate text-xs text-bmw-muted">{row.note ?? "—"}</TD></TR>)}</TBody></Table></section>
    <footer className="sticky bottom-0 z-10 flex flex-wrap justify-between gap-3 border-t border-bmw-cardBorder bg-bmw-card/95 p-3 text-sm backdrop-blur"><span>وارد: <b>{totals.inbound}</b></span><span>صادر: <b>{totals.outbound}</b></span><span>إجمالي البيع: <b>{formatMoney(totals.sales)} {CURRENCY}</b></span><span>إجمالي التكلفة: <b>{formatMoney(totals.cost)} {CURRENCY}</b></span><span>الرصيد النهائي: <b className="text-bmw-blue">{filtered.at(0)?.balanceAfter ?? part.stockQuantity}</b></span></footer>
    {invoiceTarget ? <LedgerInvoiceActionModal invoiceId={invoiceTarget.id} invoiceNumber={invoiceTarget.number} canVoid={canVoid} onClose={() => setInvoiceTarget(null)} onDone={() => { setInvoiceTarget(null); router.refresh(); }} /> : null}
    {printRequested ? <section id="printable-area" className="invoice-print-page invoice-a4" dir="rtl"><header className="invoice-header"><div><h1>الشافعي لقطع غيار BMW</h1><p>دفتر حركة صنف تفصيلي</p></div><div className="invoice-title"><h2>{part.nameAr}</h2><p>{part.oemNumber}</p></div></header><table className="invoice-lines"><thead><tr><th>التاريخ</th><th>الحركة</th><th>وارد</th><th>صادر</th><th>الرصيد</th><th>الفاتورة</th><th>الحساب</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}><td>{formatDateTime(row.createdAt)}</td><td>{ARABIC_LABELS.stockReason[row.reason]}</td><td>{Math.max(0, row.quantityDelta) || "—"}</td><td>{Math.abs(Math.min(0, row.quantityDelta)) || "—"}</td><td>{row.balanceAfter}</td><td>{row.invoiceNumber ?? "—"}</td><td>{row.partyName ?? "—"}</td></tr>)}</tbody></table></section> : null}
  </main>;
}

function LedgerInvoiceActionModal({ invoiceId, invoiceNumber, canVoid, onClose, onDone }: { invoiceId: string; invoiceNumber: string; canVoid: boolean; onClose: () => void; onDone: () => void }) {
  const router = useRouter();
  const [detail, setDetail] = useState<InvoiceDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [reason, setReason] = useState("");
  const [voiding, setVoiding] = useState(false);
  useEffect(() => { let active = true; void getInvoiceDetailAction(invoiceId).then((result) => { if (!active) return; if (result.success) setDetail(result.data); else setError(result.error); }); return () => { active = false; }; }, [invoiceId]);
  const voidInvoice = async () => { setError(null); setVoiding(true); const result = await voidInvoiceAction({ invoiceId, reason }); setVoiding(false); if (!result.success) { setError(result.error); return; } onDone(); };
  return <Modal open onClose={onClose} title={`تفاصيل الفاتورة — ${invoiceNumber}`} description="عرض وتعديل أو إلغاء المستند المرتبط بحركة الصنف دون مغادرة دفتر الحركة." size="lg" footer={<><Button variant="ghost" onClick={onClose} disabled={voiding}>إغلاق</Button>{detail ? <Button variant="outline" onClick={() => router.push(`/invoices/${detail.type === "SALE" ? "sales" : "purchases"}/${detail.id}/edit`)}><Pencil size={15} /> تعديل الفاتورة</Button> : null}</>}>
    <div className="space-y-4">{error ? <Alert variant="error">{error}</Alert> : null}{!detail && !error ? <p className="text-xs text-bmw-muted">جاري تحميل الفاتورة…</p> : null}{detail ? <><div className="grid gap-2 sm:grid-cols-4"><div className="rounded-lg border border-bmw-cardBorder bg-bmw-carbon p-2 text-xs"><span className="text-bmw-muted">الحساب</span><p className="font-bold text-white">{detail.account.name}</p></div><div className="rounded-lg border border-bmw-cardBorder bg-bmw-carbon p-2 text-xs"><span className="text-bmw-muted">الخزينة</span><p className="font-bold text-white">{detail.treasury?.name ?? "—"}</p></div><div className="rounded-lg border border-bmw-cardBorder bg-bmw-carbon p-2 text-xs"><span className="text-bmw-muted">الإجمالي</span><p className="tabular font-bold text-white">{formatMoney(detail.grandTotal)}</p></div><div className="rounded-lg border border-bmw-cardBorder bg-bmw-carbon p-2 text-xs"><span className="text-bmw-muted">المتبقي</span><p className="tabular font-bold text-amber-400">{formatMoney(detail.remainingAmount)}</p></div></div><Table><THead><TR><TH>الصنف</TH><TH>OEM</TH><TH>الكمية</TH><TH>السعر</TH><TH>الإجمالي</TH></TR></THead><TBody>{detail.items.map((item) => <TR key={item.id}><TD className="font-bold text-white">{item.nameAr}</TD><TD className="font-mono text-xs text-bmw-blue">{formatOemNumber(item.oemNumber)}</TD><TD className="tabular">{item.quantity}</TD><TD className="tabular">{formatMoney(item.unitPrice)}</TD><TD className="tabular font-bold">{formatMoney(item.totalPrice)}</TD></TR>)}</TBody></Table>{canVoid && !detail.isVoided ? <div className="rounded-xl border border-bmw-mRed/30 bg-bmw-mRed/5 p-3"><p className="mb-2 text-xs text-bmw-mRed">إلغاء الفاتورة ينشئ قيوداً عكسية للمخزون والخزينة والحساب ولا يحذف السجل.</p><Field label="سبب الإلغاء" required><Textarea rows={2} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="سبب واضح من ٥ أحرف على الأقل" /></Field><Button variant="danger" className="mt-3" onClick={() => void voidInvoice()} loading={voiding} disabled={reason.trim().length < 5}><Ban size={15} /> إلغاء الفاتورة</Button></div> : null}</> : null}</div>
  </Modal>;
}
